name: discovering-disease-outbreaks
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - Unidecode=1.3.6
  - pip=23.2.1
  - Pillow=10.0.0
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.7.0
  - nbconvert=7.7.3
  - pip:
      - geonamescache==1.3.0
      - geopy==2.3.0  # Added for proper geocoding
